use_frameworks!
platform :ios, '9.0'

target 'DopamineKit_Example' do
    pod 'DopamineKit', :path => '../'
    
    target 'DopamineKit_ReleaseTests' do
        inherit! :search_paths
    end
    
    target 'DopamineKit_ReleaseUITests' do
        inherit! :search_paths
    end
    
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'DopamineKit'
            target.build_configurations.each do |config|
                if config.name == 'Debug'
                    config.build_settings['OTHER_SWIFT_FLAGS'] = '-DDEBUG'
                end
            end
        end
    end
end
