use_frameworks!
platform :ios, '9.0'

target 'DopamineKit_Example' do
    pod 'DopamineKit', :path => '../'
end

target 'DopamineKit_Tests' do
    pod 'DopamineKit', :path => '../'
end

target 'DopamineKit_SwizzleTests' do
    pod 'DopamineKit', :path => '../'
end

target 'DopamineKit_RewardUITests' do
    pod 'DopamineKit', :path => '../'
end

target 'DopamineKit_ExampleUITests' do
    pod 'DopamineKit', :path => '../'
end

target 'DopamineKit_ReleaseTests' do
    pod 'DopamineKit', :path => '../'
end

target 'DopamineKit_ReleaseUITests' do
    pod 'DopamineKit', :path => '../'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'DopamineKit'
            target.build_configurations.each do |config|
                if config.name == 'Debug'
                    config.build_settings['OTHER_SWIFT_FLAGS'] = '-DDEBUG'
                end
            end
        end
    end
end
